spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop; #MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
        ddl-auto: create #none
#    show_sql: true #sout
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug #logger
#    org.hibernate.type: trace
    p6spy: info